DEFFUNC('x', VAR, empty_func, diff_var)
DEFFUNC(0, NUMBER, empty_func, diff_number)
DEFFUNC('+', ADD, empty_func, diff_add)
DEFFUNC('-', SUB, empty_func, diff_sub)
DEFFUNC('*', MUL, empty_func, diff_mul)
DEFFUNC('/', DIV, empty_func, diff_div)
DEFFUNC('^', POW, empty_func, diff_pow)
DEFFUNC('l', LN, push_ln, diff_ln)
